### PR TITLE
docs: add auto load nvimTree

### PR DESCRIPTION
**Pull request by ghost**
Please add this useful information in the documentation.

### CODE REVIEW

**Comment by natecraddock** [comment]
I like this idea! I'll think about if it makes sense to have an FAQ or list of configs somewhere. I will likely put it in a wiki so anyone can contribute without making PRs

**Comment by ghost** [comment]
Let me know your answer!

**Comment by natecraddock** [comment]
I decided to make a wiki since it's simpler to contribute to. I made two pages so far:

* https://github.com/natecraddock/workspaces.nvim/wiki/Configuration-Recipes
* https://github.com/natecraddock/workspaces.nvim/wiki/Troubleshooting

Feel free to edit!

**Comment by ghost** [comment]
Perfect! many people will be helped with this!

**Pull request closed without merging**
